<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Deloitte\WebsiteSwitcher\Block\Switcher $block */
?>
<?php if (count($block->getWebsites()) > 1) : ?>
    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-languages<?= $block->escapeHtmlAttr($id) ?>">
        <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Website')) ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <div class="action toggle switcher-trigger" id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" data-trigger-keypress-button="true">
                <strong class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?>">
                    <span><?= $block->escapeHtml($block->getWebsiteName()) ?></span>
                </strong>
            </div>

            <ul class="dropdown switcher-dropdown" data-target="dropdown">
                <?php foreach ($block->getWebsites() as $_lang) : ?>
                    <?php if ($_lang->getName() != $block->getWebsiteName()) : ?>
                        <li class="view-switcher-option">
                            <a href="<?= $block->escapeUrl($block->getWebsiteUrl($_lang->getId())) ?>">
                                <?= $block->escapeHtml($_lang->getName()) ?>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
<?php endif; ?>